Patch 3 (#3)
* remove unused

* various improvements

- fix typo
- avoid abiguous upper conver
- simplify tuple implementation

* revert to wimdows 2019
trying to fix fatal error C1001 on Build Engine version 17.2.1+52cd2da31

* simplify implementation

* temporary fix for zero sized optimized tuple

* ebco fix for msvc

* improve new derive

* avoid abiguous method

* fix clone_from

* add zero sized type convertible